
-- DROP DATABASE Planazo;
-- CREATE DATABASE IF NOT EXISTS Planazo;
-- USE Planazo;

INSERT INTO USUARIO (Nombre, Email, Password) VALUES
('María Jiménez', 'mariajimenez@gmail.com', 'maria1234'),
('Juan Pérez', 'juanperez@gmail.com', 'juan1234'),
('Ana López', 'analopez@gmail.com', 'ana1234'),
('Roberto García', 'robertogarcia@gmail.com', 'roberto1234'),
('Laura Martínez', 'lauramartinez@gmail.com', 'laura1234'),
('Carlos Hernández', 'carloshernandez@gmail.com', 'carlos1234'),
('Patricia González', 'patriciagonzalez@gmail.com', 'patricia1234'),
('Fernando Álvarez', 'fernandoalvarez@gmail.com', 'fernando1234'),
('Carmen Ruiz', 'carmenruiz@gmail.com', 'carmen1234'),
('Sergio Moreno', 'sergiomoreno@gmail.com', 'sergio1234');

INSERT INTO USUARIO_ROL (Usuario_id, Rol) VALUES
(1, 'ROL_ADMIN'),
(2, 'ROL_ADMIN'),
(3, 'ROL_USER'),
(4, 'ROL_USER'),
(5, 'ROL_USER'),
(6, 'ROL_USER'),
(7, 'ROL_USER'),
(8, 'ROL_USER'),
(9, 'ROL_USER'),
(10, 'ROL_USER');

INSERT INTO DESTINO (Nombre, Imagen) VALUES
('Almería', 'assets/destinos/01.jpg'),
('Cádiz', 'assets/destinos/02.jpg'),
('Córdoba', 'assets/destinos/03.jpg'),
('Granada', 'assets/destinos/04.jpg'),
('Huelva', 'assets/destinos/05.jpg'),
('Jaén', 'assets/destinos/06.jpg'),
('Málaga', 'assets/destinos/07.jpg'),
('Sevilla', 'assets/destinos/08.jpg');

INSERT INTO ACTIVIDAD (Nombre, Descripcion, Categoria, Puntuacion, Direccion, Horario, Imagen, Destino_id) VALUES
('Visita al Parque Natural Cabo de Gata-Níjar', 'Explora la belleza natural del Cabo de Gata, sus playas y paisajes volcánicos.', 'NATURALEZA', 2.3, 'Cabo de Gata, Almería', 'Todo el día', 'src/assets/actividades/01/01.jpg', 1),
('Tour por el Conjunto Monumental de la Alcazaba', 'Descubre la historia de Almería a través de su impresionante fortaleza musulmana.', 'CULTURA', 3.4, 'Alcazaba, Almería', '09:00-18:00', 'src/assets/actividades/01/02.jpg', 1),
('Degustación de tapas en la capital', 'Saborea las mejores tapas almerienses en un tour gastronómico por la ciudad.', 'GASTRONOMÍA', 5.0, 'Centro de Almería', '12:00-16:00, 20:00-24:00', 'src/assets/actividades/01/03.jpg', 1),
('Rutas de senderismo en Sierra de los Filabres', 'Disfruta de la naturaleza y el ejercicio con rutas de senderismo por la Sierra de los Filabres.', 'DEPORTE', 5.0, 'Sierra de los Filabres, Almería', 'Todo el día', 'src/assets/actividades/01/04.jpg', 1),
('Noche de flamenco en un tablao local', 'Vive la pasión del flamenco en una auténtica noche almeriense.', 'OCIO', 4.5, 'Tablao en Almería', '21:00-23:00', 'src/assets/actividades/01/05.jpg', 1),
('Kayak en las calas de Cabo de Gata', 'Recorre en kayak algunas de las calas más hermosas y accesibles solo por mar del Parque Natural Cabo de Gata-Níjar.', 'NATURALEZA', 4.9, 'Parque Natural Cabo de Gata, Almería', '10:00-14:00', 'src/assets/actividades/01/06.jpg', 1),
('Visita al Museo de Almería', 'Explora la rica historia de Almería desde la prehistoria hasta la época moderna en su museo provincial.', 'CULTURA', 4.5, 'Museo de Almería, Almería', '09:00-20:00', 'src/assets/actividades/01/07.jpg', 1),
('Ruta de vinos por la Alpujarra Almeriense', 'Disfruta de una jornada de enoturismo descubriendo los vinos de la Alpujarra Almeriense.', 'GASTRONOMÍA', 3.4, 'Alpujarra de Almería, Almería', '11:00-16:00', 'src/assets/actividades/01/08.jpg', 1),
('Buceo en el arrecife de las Sirenas', 'Sumérgete en las aguas cristalinas del Cabo de Gata y explora el famoso arrecife de las Sirenas.', 'DEPORTE', 4.6, 'Arrecife de las Sirenas, Cabo de Gata, Almería', '09:00-17:00', 'src/assets/actividades/01/09.jpg', 1),
('Cine al aire libre en la playa de los Genoveses', 'Disfruta de una noche de cine bajo las estrellas en una de las playas más emblemáticas de Almería.', 'OCIO', 3.9, 'Playa de los Genoveses, Cabo de Gata, Almería', '21:00-23:00', 'src/assets/actividades/01/10.jpg', 1),
('Observación de aves en el Parque Natural de Doñana', 'Experimenta la diversidad de aves en uno de los humedales más importantes de Europa.', 'NATURALEZA', 4.5, 'Parque Natural de Doñana, Cádiz', '08:00-18:00', 'src/assets/actividades/02/01.jpg', 2),
('Paseo por el Parque Natural de la Breña y Marismas del Barbate', 'Disfruta de un paseo por este parque natural, que ofrece unas vistas espectaculares de la costa y de la sierra.', 'NATURALEZA', 5.0, 'Parque Natural de la Breña, Cádiz', 'Todo el día', 'src/assets/actividades/02/02.jpg', 2),
('Visita a la Catedral de Cádiz', 'Descubre la historia y la arquitectura de la impresionante Catedral de Cádiz.', 'CULTURA', 4.5, 'Catedral de Cádiz, Cádiz', '10:00-18:00', 'src/assets/actividades/02/03.jpg', 2),
('Recorrido por el Teatro Romano de Cádiz', 'Explora uno de los teatros romanos más antiguos descubiertos en España.', 'CULTURA', 2.0, 'Teatro Romano de Cádiz, Cádiz', '09:00-19:00', 'src/assets/actividades/02/04.jpg', 2),
('Ruta del atún rojo en Barbate', 'Saborea el atún rojo en diferentes preparaciones, una especialidad local de Barbate.', 'GASTRONOMÍA', 2.9, 'Barbate, Cádiz', '12:00-16:00, 19:00-23:00', 'src/assets/actividades/02/05.jpg', 2),
('Degustación de vinos de Jerez', 'Descubre los secretos de los vinos de Jerez con una visita a una bodega local.', 'GASTRONOMÍA', 3.8, 'Jerez de la Frontera, Cádiz', '11:00-14:00, 17:00-19:00', 'src/assets/actividades/02/06.jpg', 2),
('Surf en la playa de Tarifa', 'Atrévete a surfear en las playas de Tarifa, conocidas mundialmente por sus excelentes condiciones para el windsurf y el kitesurf.', 'DEPORTE', 4.5, 'Playa de Tarifa, Cádiz', 'Todo el día', 'src/assets/actividades/02/07.jpg', 2),
('Rutas a caballo en la Sierra de Grazalema', 'Disfruta de una ruta a caballo por los paisajes únicos de la Sierra de Grazalema.', 'DEPORTE', 5.0, 'Sierra de Grazalema, Cádiz', '09:00-14:00', 'src/assets/actividades/02/08.jpg', 2),
('Espectáculo ecuestre en la Real Escuela Andaluza del Arte Ecuestre', 'Maravíllate con un espectáculo de danza ecuestre que muestra la tradición y habilidad de la equitación andaluza.', 'OCIO', 5.0, 'Real Escuela Andaluza del Arte Ecuestre, Jerez de la Frontera, Cádiz', '12:00-14:00', 'src/assets/actividades/02/09.jpg',2),
('Carnaval de Cádiz', 'Sumérgete en el ambiente festivo del Carnaval de Cádiz, uno de los más famosos y divertidos de España.', 'OCIO', 4.5, 'Calles de Cádiz, Cádiz', 'Variable, principalmente en febrero', 'src/assets/actividades/02/10.jpg', 2),
('Visita a la Mezquita-Catedral de Córdoba', 'Explora este icónico monumento que combina estilos arquitectónicos islámicos y cristianos.', 'CULTURA', 4.8, 'Mezquita-Catedral, Córdoba', '10:00-19:00', 'src/assets/actividades/03/01.jpg', 3),
('Paseo por el Alcázar de los Reyes Cristianos', 'Descubre la historia de Córdoba en este palacio fortificado con hermosos jardines.', 'CULTURA', 5.0, 'Alcázar de los Reyes Cristianos, Córdoba', '09:30-19:00', 'src/assets/actividades/03/02.jpg', 3),
('Degustación de salmorejo cordobés', 'Prueba este plato típico de Córdoba, una deliciosa crema fría de tomate y pan.', 'GASTRONOMÍA', 4.6, 'Restaurantes locales, Córdoba', '12:00-16:00, 20:00-24:00', 'src/assets/actividades/03/03.jpg', 3),
('Ruta de tapas por el casco antiguo', 'Disfruta de las mejores tapas en una ruta gastronómica por el corazón de Córdoba.', 'GASTRONOMÍA', 4.7, 'Casco antiguo, Córdoba', '13:00-16:00, 20:00-23:00', 'src/assets/actividades/03/04.jpg', 3),
('Senderismo en la Sierra de Córdoba', 'Conecta con la naturaleza en una ruta de senderismo por la Sierra de Córdoba.', 'NATURALEZA', 4.8, 'Sierra de Córdoba', 'Todo el día', 'src/assets/actividades/03/05.jpg', 3),
('Observación de estrellas en Los Villares', 'Experimenta la astronomía observando las estrellas en el parque periurbano de Los Villares.', 'NATURALEZA', 4.8, 'Parque Los Villares, Córdoba', '20:00-00:00', 'src/assets/actividades/03/06.jpg', 3),
('Espectáculo flamenco en Tablao Cordobés', 'Vive la pasión del flamenco en un auténtico tablao de Córdoba.', 'OCIO', 3.4, 'Tablao Cordobés, Córdoba', '21:00-23:00', 'src/assets/actividades/03/07.jpg', 3),
('Noche de baños árabes', 'Relájate en los baños árabes de Córdoba, una experiencia de ocio y bienestar única.', 'OCIO', 3.5, 'Baños Árabes, Córdoba', '10:00-22:00', 'src/assets/actividades/03/08.jpg', 3),
('Ciclismo por la Vía Verde de la Subbética', 'Disfruta de un día de ciclismo por esta ruta que atraviesa paisajes naturales impresionantes.', 'DEPORTE', 3.7, 'Vía Verde de la Subbética, Córdoba', 'Todo el día', 'src/assets/actividades/03/09.jpg', 3),
('Golf en el Club de Campo de Córdoba', 'Practica tu swing en uno de los campos de golf más bonitos de la región.', 'DEPORTE', 5.0, 'Club de Campo, Córdoba', '08:00-20:00', 'src/assets/actividades/03/10.jpg', 3),
('Visita a la Alhambra y el Generalife', 'Explora el conjunto monumental más famoso de España, con sus palacios nazaríes y jardines.', 'CULTURA', 4.7, 'Alhambra, Granada', '08:30-20:00', 'src/assets/actividades/04/01.jpg', 4),
('Recorrido por el barrio del Albaicín', 'Pasea por las calles empedradas de este antiguo barrio morisco, Patrimonio de la Humanidad.', 'CULTURA', 2.6, 'Albaicín, Granada', 'Todo el día', 'src/assets/actividades/04/02.jpg', 4),
('Esquí en Sierra Nevada', 'Disfruta de las pistas de esquí de uno de los mejores centros de esquí de España.', 'DEPORTE', 5.0, 'Sierra Nevada, Granada', '09:00-17:00', 'src/assets/actividades/04/03.jpg', 4),
('Senderismo por el Parque Nacional de Sierra Nevada', 'Conecta con la naturaleza en una de las muchas rutas de senderismo disponibles en el parque.', 'NATURALEZA', 3.4, 'Sierra Nevada, Granada', 'Todo el día', 'src/assets/actividades/04/04.jpg', 4),
('Degustación de tapas granadinas', 'Granada es famosa por sus tapas gratuitas; disfruta de una variedad en los bares locales.', 'GASTRONOMÍA', 4.6, 'Bares de Granada', '12:00-16:00, 20:00-24:00', 'src/assets/actividades/04/05.jpg', 4),
('Visita a las cuevas del Sacromonte', 'Descubre las tradicionales casas cueva de Granada y disfruta de un espectáculo flamenco.', 'CULTURA', 1.2, 'Sacromonte, Granada', '10:00-22:00', 'src/assets/actividades/04/06.jpg', 4),
('Baño en los Baños Árabes', 'Relájate en un baño árabe histórico para una experiencia de bienestar tradicional.', 'OCIO', 1.3, 'Baños Árabes, Granada', '10:00-22:00', 'src/assets/actividades/03/08.jpg_GRANADA', 4),
('Noche de jazz en el Eshavira Club', 'Disfruta de la mejor música jazz en uno de los clubes más emblemáticos de Granada.', 'OCIO', 4.3, 'Eshavira Club, Granada', '21:00-01:00', 'src/assets/actividades/04/08.jpg', 4),
('Ruta de arte callejero en Realejo', 'Explora el barrio del Realejo y admira el arte callejero que decora sus paredes.', 'CULTURA', 5.0, 'Realejo, Granada', 'Todo el día', 'src/assets/actividades/04/09.jpg', 4),
('Cata de vinos en la Alpujarra Granadina', 'Descubre los vinos de la región con una cata en las bodegas de la Alpujarra.', 'GASTRONOMÍA', 5.0, 'Alpujarra Granadina, Granada', '11:00-14:00', 'src/assets/actividades/01/08.jpg', 4),
('Visita al Parque Nacional de Doñana', 'Explora uno de los parques nacionales más importantes de Europa, hogar de una rica biodiversidad.', 'NATURALEZA', 1.4, 'Parque Nacional de Doñana, Huelva', '09:00-19:00', 'src/assets/actividades/05/01.jpg', 5),
('Ruta del Jamón Ibérico en Jabugo', 'Descubre el proceso de elaboración del jamón ibérico y disfruta de una degustación en Jabugo.', 'GASTRONOMÍA', 4.5, 'Jabugo, Huelva', '10:00-14:00', 'src/assets/actividades/05/02.jpg', 5),
('Kitesurf en la playa de El Portil', 'Practica kitesurf en las aguas de El Portil, un destino conocido por sus excelentes condiciones.', 'DEPORTE', 4.1, 'Playa de El Portil, Huelva', 'Todo el día', 'src/assets/actividades/05/03.jpg', 5),
('Visita a la Gruta de las Maravillas', 'Maravíllate con las formaciones de estalactitas y estalagmitas en esta espectacular cueva.', 'NATURALEZA', 3.2, 'Gruta de las Maravillas, Huelva', '10:00-18:00', 'src/assets/actividades/05/04.jpg', 5),
('Recorrido por el Barrio Obrero de Huelva', 'Conoce la historia y la arquitectura del emblemático Barrio Obrero, símbolo de la industrialización.', 'CULTURA', 3.3, 'Barrio Obrero, Huelva', 'Todo el día', 'src/assets/actividades/05/05.jpg', 5),
('Cata de vinos del Condado de Huelva', 'Participa en una cata de los exquisitos vinos de la denominación de origen Condado de Huelva.', 'GASTRONOMÍA', 4.9, 'Condado de Huelva', '12:00-14:00', 'src/assets/actividades/05/06.jpg', 5),
('Paseo en barco por la Ría de Huelva', 'Disfruta de un relajante paseo en barco por la Ría de Huelva, con vistas a la marisma y la ciudad.', 'OCIO', 4.6, 'Ría de Huelva', '16:00-19:00', 'src/assets/actividades/05/07.jpg', 5),
('Visita al Muelle de las Carabelas', 'Descubre réplicas de las tres carabelas de Colón en este museo al aire libre dedicado al Descubrimiento de América.', 'CULTURA', 2.5, 'Muelle de las Carabelas, Huelva', '09:00-20:00', 'src/assets/actividades/05/08.jpg', 5),
('Golf en el Club de Golf Bellavista', 'Disfruta de una jornada de golf en uno de los clubes más antiguos y prestigiosos de Andalucía.', 'DEPORTE', 3.4, 'Club de Golf Bellavista, Huelva', '08:00-20:00', 'src/assets/actividades/05/09.jpg', 5),
('Festival de Cine Iberoamericano', 'No te pierdas este importante festival que reúne las mejores producciones cinematográficas iberoamericanas.', 'OCIO', 1.8, 'Huelva', 'Variable según programación', 'src/assets/actividades/05/10.jpg', 5),
('Visita al Castillo de Santa Catalina', 'Descubre la historia y las vistas panorámicas de Jaén desde este icónico castillo.', 'CULTURA', 5.0, 'Castillo de Santa Catalina, Jaén', '09:00-21:00', 'src/assets/actividades/06/01.jpg', 6),
('Ruta de aceite de oliva', 'Explora las almazaras y degusta algunos de los mejores aceites de oliva del mundo.', 'GASTRONOMÍA', 5.0, 'Provincia de Jaén', '10:00-14:00', 'src/assets/actividades/06/02.jpg', 6),
('Senderismo en el Parque Natural de Cazorla', 'Conecta con la naturaleza en uno de los mayores parques naturales de España.', 'NATURALEZA', 3.6, 'Parque Natural de Cazorla, Jaén', 'Todo el día', 'src/assets/actividades/06/03.jpg', 6),
('Baños árabes en Jaén', 'Relájate en los antiguos baños árabes mejor conservados de Europa.', 'OCIO', 3.6, 'Baños Árabes, Jaén', '10:00-20:00', 'src/assets/actividades/03/08.jpg_JAEN', 6),
('Kayak en el Embalse del Tranco', 'Disfruta de un día de kayak en las tranquilas aguas del Embalse del Tranco.', 'DEPORTE', 4.2, 'Embalse del Tranco, Jaén', '10:00-18:00', 'src/assets/actividades/06/05.jpg', 6),
('Visita a la Catedral de Jaén', 'Explora esta joya del renacimiento español y su impresionante sacristía.', 'CULTURA', 3.0, 'Catedral de Jaén, Jaén', '09:00-19:00', 'src/assets/actividades/06/06.jpg', 6),
('Ruta por el casco antiguo de Úbeda', 'Descubre el patrimonio renacentista de Úbeda, ciudad Patrimonio de la Humanidad.', 'CULTURA', 4.0, 'Casco antiguo de Úbeda, Jaén', 'Todo el día', 'src/assets/actividades/06/07.jpg', 6),
('Parapente en Sierra Mágina', 'Vive la emoción de volar en parapente sobre los impresionantes paisajes de Sierra Mágina.', 'DEPORTE', 4.4, 'Sierra Mágina, Jaén', '09:00-18:00', 'src/assets/actividades/06/08.jpg', 6),
('Degustación gastronómica en Baeza', 'Saborea la cocina local en Baeza, otra ciudad renacentista de Jaén.', 'GASTRONOMÍA', 2.7, 'Baeza, Jaén', '12:00-16:00, 19:00-23:00', 'src/assets/actividades/06/09.jpg', 6),
('Observación de estrellas en Sierra Morena', 'Descubre el cielo nocturno en una de las mejores zonas de España para la observación de estrellas.', 'NATURALEZA', 2.2, 'Sierra Morena, Jaén', '21:00-01:00', 'src/assets/actividades/06/10.jpg', 6),
('Visita al Museo Picasso', 'Explora el legado de Pablo Picasso en su ciudad natal, a través de una de las colecciones más completas de sus obras.', 'CULTURA', 2.6, 'Museo Picasso, Málaga', '10:00-19:00', 'src/assets/actividades/07/01.jpg', 7),
('Recorrido por el Caminito del Rey', 'Atrévete a caminar por este impresionante sendero colgante, conocido como uno de los más peligrosos del mundo antes de su restauración.', 'NATURALEZA', 4.8, 'Caminito del Rey, Málaga', '09:30-16:00', 'src/assets/actividades/07/02.jpg', 7),
('Degustación de vinos en Ronda', 'Descubre los vinos de la Serranía de Ronda con una visita a una bodega local y una cata de sus mejores caldos.', 'GASTRONOMÍA', 3.6, 'Ronda, Málaga', '11:00-14:00', 'src/assets/actividades/07/03.jpg', 7),
('Baños Árabes en el Hammam Al Ándalus', 'Revive la tradición de los baños árabes en este hammam que recrea la atmósfera y la arquitectura de los antiguos baños de Al Ándalus.', 'OCIO', 3.3, 'Hammam Al Ándalus, Málaga', '10:00-22:00', 'src/assets/actividades/07/04.jpg', 7),
('Espeleología en la Cueva de Nerja', 'Explora las maravillas subterráneas de la Cueva de Nerja, uno de los yacimientos prehistóricos más importantes de España.', 'NATURALEZA', 4.6, 'Cueva de Nerja, Málaga', '09:30-16:30', 'src/assets/actividades/07/05.jpg', 7),
('Paseo en barco por la Costa del Sol', 'Disfruta de un día en el mar con un paseo en barco que te ofrece vistas espectaculares de la Costa del Sol.', 'OCIO', 2.3, 'Costa del Sol, Málaga', '11:00-14:00', 'src/assets/actividades/07/06.jpg', 7),
('Clase de cocina andaluza', 'Aprende a preparar platos típicos andaluces en una clase de cocina con un chef local.', 'GASTRONOMÍA', 5.0, 'Málaga', '17:00-20:00', 'src/assets/actividades/07/07.jpg', 7),
('Ruta de senderismo en el Torcal de Antequera', 'Descubre las formaciones rocosas únicas del Torcal de Antequera, un paraje natural de extraordinaria belleza.', 'NATURALEZA', 5.0, 'Torcal de Antequera, Málaga', '09:00-17:00', 'src/assets/actividades/07/08.jpg', 7),
('Noche de flamenco en el Tablao Los Amayas', 'Vive la intensidad y pasión del flamenco en uno de los tablaos más auténticos de Málaga.', 'OCIO', 4.4, 'Tablao Los Amayas, Málaga', '21:00-23:00', 'src/assets/actividades/07/09.jpg', 7),
('Visita al Jardín Botánico-Histórico La Concepción', 'Pasea por uno de los jardines tropicales y subtropicales más bellos de España, con más de 150 años de historia.', 'NATURALEZA', 3.2, 'Jardín Botánico-Histórico La Concepción, Málaga', '09:30-19:30', 'src/assets/actividades/07/10.jpg', 7),
('Visita a la Catedral de Sevilla y la Giralda', 'Descubre la majestuosidad de la Catedral de Sevilla, el mayor edificio gótico del mundo, y sube a su icónica torre, la Giralda.', 'CULTURA', 5.0, 'Catedral de Sevilla, Sevilla', '09:30-16:00', 'src/assets/actividades/08/01.jpg', 8),
('Paseo por el Parque de María Luisa y Plaza de España', 'Disfruta de un relajante paseo por el Parque de María Luisa hasta llegar a la impresionante Plaza de España.', 'NATURALEZA', 4.8, 'Parque de María Luisa, Sevilla', 'Todo el día', 'src/assets/actividades/08/02.jpg', 8),
('Espectáculo de flamenco en el Barrio de Triana', 'Vive la pasión del flamenco en uno de los barrios más emblemáticos de Sevilla, cuna de grandes artistas.', 'OCIO', 4.3, 'Barrio de Triana, Sevilla', '21:00-23:00', 'src/assets/actividades/08/03.jpg', 8),
('Crucero por el río Guadalquivir', 'Disfruta de las mejores vistas de Sevilla desde el río Guadalquivir en un tranquilo crucero.', 'OCIO', 5.0, 'Río Guadalquivir, Sevilla', '11:00-18:00', 'src/assets/actividades/08/04.jpg', 8),
('Visita al Real Alcázar de Sevilla', 'Explora uno de los palacios en uso más antiguos del mundo, ejemplo sublime de la arquitectura mudéjar en España.', 'CULTURA', 3.5, 'Real Alcázar, Sevilla', '09:30-19:00', 'src/assets/actividades/08/05.jpg', 8),
('Tour de tapas por Sevilla', 'Sumérgete en la cultura gastronómica sevillana con un tour de tapas por los mejores bares de la ciudad.', 'GASTRONOMÍA', 5.0, 'Centro de Sevilla', '13:00-16:00, 20:00-23:00', 'src/assets/actividades/08/06.jpg', 8),
('Kayak en el río Guadalquivir', 'Explora Sevilla desde una perspectiva diferente, remando por el río Guadalquivir.', 'DEPORTE', 4.3, 'Río Guadalquivir, Sevilla', '10:00-18:00', 'src/assets/actividades/08/07.jpg', 8),
('Ciclismo por la Isla de la Cartuja', 'Recorre en bicicleta la Isla de la Cartuja, disfrutando de sus parques y arquitectura contemporánea.', 'DEPORTE', 5.0, 'Isla de la Cartuja, Sevilla', 'Todo el día', 'src/assets/actividades/08/08.jpg', 8),
('Visita al Museo de Bellas Artes', 'Contempla obras maestras del arte barroco español en uno de los museos más importantes de España.', 'CULTURA', 3.9, 'Museo de Bellas Artes, Sevilla', '09:00-21:00', 'src/assets/actividades/08/09.jpg', 8),
('Ruta por el casco antiguo de Sevilla', 'Descubre la historia y los secretos del casco antiguo de Sevilla, uno de los más grandes de Europa.', 'CULTURA', 5.0, 'Casco antiguo, Sevilla', 'Todo el día', 'src/assets/actividades/08/10.jpg', 8);






INSERT INTO COMENTARIO (descripcion, puntuacion, titulo, actividad_id, usuario_id) VALUES
('Una experiencia única en la naturaleza, altamente recomendada.', 4.5, 'Experiencia inolvidable en Cabo de Gata', 1, 2),
('Impresionante vista desde la fortaleza, lleno de historia.', 4.8, 'Visita a la Alcazaba', 2, 1),
('Las mejores tapas que he probado, gran variedad.', 5.0, 'Ruta de tapas', 3, 2),
('Ruta desafiante pero gratificante, paisajes hermosos.', 4.7, 'Senderismo en Sierra Filabres', 4, 1),
('El ambiente del tablao es auténtico, y el espectáculo emocionante.', 4.9, 'Noche de flamenco', 5, 2),
('La tranquilidad de las calas es inigualable, el kayak es una forma estupenda de explorarlas.', 4.8, 'Kayak en Cabo de Gata', 6, 1),
('El museo ofrece una visión profunda de la historia de Almería.', 4.0, 'Cultura e historia', 7, 2),
('Una introducción perfecta a los vinos de la región, muy informativo.', 4.6, 'Ruta del vino', 8, 1),
('La diversidad y belleza del arrecife es impresionante, una gran experiencia de buceo.', 4.7, 'Buceo en las Sirenas', 9, 2),
('Ver una película bajo las estrellas en la playa fue mágico.', 4.5, 'Cine al aire libre', 10, 1),
('Una manera perfecta de conocer la historia local.', 4.2, 'Enriquecedor', 11, 3),
('No podía creer la belleza del lugar, absolutamente impresionante.', 4.9, 'Naturaleza pura', 12, 4),
('La guía era muy conocedora y amable.', 4.3, 'Tour informativo', 13, 5),
('Una de las mejores experiencias culinarias de mi vida.', 5.0, 'Gastronomía excepcional', 14, 6),
('Perfecto para los amantes del vino.', 4.6, 'Tour del vino inolvidable', 15, 7),
('Las vistas desde la cima son impresionantes.', 4.7, 'Aventura en la montaña', 16, 8),
('El espectáculo capturó la esencia del flamenco.', 4.8, 'Noche mágica', 17, 9),
('Un desafío físico, pero vale totalmente la pena.', 4.4, 'Senderismo extremo', 18, 10),
('Maravillosa manera de pasar la tarde.', 4.0, 'Día relajante', 19, 1),
('Gran diversidad de aves, traigan sus binoculares.', 4.5, 'Observación de aves', 20, 2),
('El guía hizo que la historia cobrara vida.', 4.8, 'Viaje histórico', 21, 3),
('Una joya oculta, no se lo pierdan.', 4.9, 'Descubrimiento increíble', 22, 4),
('Perfecto para familias y fotógrafos.', 4.3, 'Paisajes de ensueño', 23, 5),
('Los mejores mariscos que he probado.', 5.0, 'Delicia marina', 24, 6),
('Una experiencia cultural profunda.', 4.7, 'Inmersión cultural', 25, 7),
('Hermoso lugar para reflexionar y relajarse.', 4.6, 'Paz y serenidad', 26, 8),
('Ideal para los amantes de la naturaleza y la tranquilidad.', 4.5, 'Retiro natural', 27, 9),
('La arquitectura y el arte te dejan sin aliento.', 4.9, 'Belleza arquitectónica', 28, 10),
('Aprender sobre el proceso de producción fue fascinante.', 4.4, 'Tour educativo', 29, 1),
('Una excelente manera de ver la ciudad desde otra perspectiva.', 4.8, 'Aventura urbana', 30, 2),
('Los guías fueron increíblemente amables y sabían mucho.', 4.5, 'Experiencia inigualable', 31, 1),
('¡Ver las estrellas nunca había sido tan emocionante!', 4.7, 'Noche estrellada', 32, 2),
('Aprender surf fue desafiante pero muy divertido.', 4.3, 'Surf al máximo', 33, 3),
('La comida era deliciosa y el ambiente increíble.', 4.8, 'Cena espectacular', 34, 4),
('La ruta de senderismo fue bien planeada y hermosa.', 4.6, 'Aventura escénica', 35, 5),
('Nunca había visto un espectáculo de flamenco tan apasionante.', 5.0, 'Noche de pasión', 36, 6),
('Las aguas termales fueron el perfecto final para nuestro día.', 4.4, 'Relajación total', 37, 7),
('La historia detrás de cada esquina era fascinante.', 4.9, 'Viaje en el tiempo', 38, 8),
('Los niños disfrutaron cada momento, especialmente el parque.', 4.3, 'Diversión familiar', 39, 9),
('El tour de vino superó todas nuestras expectativas.', 4.8, 'Experiencia vinícola', 40, 10),
('Una inmersión profunda en la cultura local, muy recomendado.', 4.7, 'Cultura viva', 41, 1),
('La mejor manera de comenzar el día, con un poco de ejercicio en un entorno hermoso.', 4.5, 'Mañana activa', 42, 2),
('Los detalles arquitectónicos y la historia son impresionantes.', 4.6, 'Maravilla arquitectónica', 43, 3),
('Perfecto para aquellos que buscan una experiencia culinaria única.', 4.8, 'Delicias locales', 44, 4),
('Hacer kayak al atardecer fue la experiencia de mi vida.', 5.0, 'Kayak al atardecer', 45, 5),
('Los murales y el arte callejero eran absolutamente impresionantes.', 4.7, 'Exploración artística', 46, 6),
('Sentir la historia tan de cerca fue una experiencia poderosa.', 4.5, 'Historia palpable', 47, 7),
('Un lugar perfecto para los fotógrafos y amantes de la naturaleza.', 4.4, 'Paraíso fotográfico', 48, 8),
('Los platos ofrecieron una explosión de sabores locales auténticos.', 4.9, 'Festival gastronómico', 49, 9),
('Una experiencia relajante, perfecta para despejar la mente.', 4.3, 'Oasis de tranquilidad', 50, 10);









