#Málaga
INSERT INTO ACTIVIDAD (Nombre, Descripción, Categoría, Puntuación, Dirección, Horario, Imagen, Destino_id) VALUES
('Visita al Museo Picasso', 'Explora el legado de Pablo Picasso en su ciudad natal, a través de una de las colecciones más completas de sus obras.', 'CULTURA', NULL, 'Museo Picasso, Málaga', '10:00-19:00', 'URL_IMAGEN_MUSEO_PICASSO', 7),
('Recorrido por el Caminito del Rey', 'Atrévete a caminar por este impresionante sendero colgante, conocido como uno de los más peligrosos del mundo antes de su restauración.', 'NATURALEZA', NULL, 'Caminito del Rey, Málaga', '09:30-16:00', 'URL_IMAGEN_CAMINITO_DEL_REY', 7),
('Degustación de vinos en Ronda', 'Descubre los vinos de la Serranía de Ronda con una visita a una bodega local y una cata de sus mejores caldos.', 'GASTRONOMÍA', NULL, 'Ronda, Málaga', '11:00-14:00', 'URL_IMAGEN_VINOS_RONDA', 7),
('Baños Árabes en el Hammam Al Ándalus', 'Revive la tradición de los baños árabes en este hammam que recrea la atmósfera y la arquitectura de los antiguos baños de Al Ándalus.', 'OCIO', NULL, 'Hammam Al Ándalus, Málaga', '10:00-22:00', 'URL_IMAGEN_HAMMAM_MALAGA', 7),
('Espeleología en la Cueva de Nerja', 'Explora las maravillas subterráneas de la Cueva de Nerja, uno de los yacimientos prehistóricos más importantes de España.', 'NATURALEZA', NULL, 'Cueva de Nerja, Málaga', '09:30-16:30', 'URL_IMAGEN_CUEVA_NERJA', 7),
('Paseo en barco por la Costa del Sol', 'Disfruta de un día en el mar con un paseo en barco que te ofrece vistas espectaculares de la Costa del Sol.', 'OCIO', NULL, 'Costa del Sol, Málaga', '11:00-14:00', 'URL_IMAGEN_BARCO_COSTA_SOL', 7),
('Clase de cocina andaluza', 'Aprende a preparar platos típicos andaluces en una clase de cocina con un chef local.', 'GASTRONOMÍA', NULL, 'Málaga', '17:00-20:00', 'URL_IMAGEN_COOKING_CLASS', 7),
('Ruta de senderismo en el Torcal de Antequera', 'Descubre las formaciones rocosas únicas del Torcal de Antequera, un paraje natural de extraordinaria belleza.', 'NATURALEZA', NULL, 'Torcal de Antequera, Málaga', '09:00-17:00', 'URL_IMAGEN_TORCAL_ANTEQUERA', 7),
('Noche de flamenco en el Tablao Los Amayas', 'Vive la intensidad y pasión del flamenco en uno de los tablaos más auténticos de Málaga.', 'OCIO', NULL, 'Tablao Los Amayas, Málaga', '21:00-23:00', 'URL_IMAGEN_FLAMENCO_MALAGA', 7),
('Visita al Jardín Botánico-Histórico La Concepción', 'Pasea por uno de los jardines tropicales y subtropicales más bellos de España, con más de 150 años de historia.', 'NATURALEZA', NULL, 'Jardín Botánico-Histórico La Concepción, Málaga', '09:30-19:30', 'URL_IMAGEN_JARDIN_CONCEPCION', 7);
